#!/usr/bin/env python3
"""Generate the sample audio briefing (macOS `say`) + sentence-level timing -> public/audio/briefing.m4a, src/data/briefing.json"""
import subprocess, wave, json, os, tempfile

VOICE = "Daniel"
CHAPTERS = [
 ("Opening", ["This is the Upheal war briefing for September twenty-ninth, twenty twenty-six.",
              "Three stories today: Ukraine, the Middle East, and Africa.",
              "All items are drawn from published reports by Al Jazeera, the BBC, and U.N. News."]),
 ("Ukraine", ["Russia struck Kyiv overnight, hitting the historic National Academy of Sciences.",
              "Footage shows people leaning out of windows as flames engulfed part of the building, according to Al Jazeera.",
              "The BBC's Paul Adams reported from the scene of the drone strike.",
              "Separately, Seoul has summoned Ukraine's envoy after President Zelensky revealed that two captured North Korean soldiers had been sent to South Korea, a transfer Seoul says was meant to remain secret."]),
 ("Middle East", ["In Yemen, the BBC gained rare access to the front line, travelling with pro-government soldiers as the Houthis battle for control of a key city.",
                  "On Iran, Foreign Minister Araghchi met Qatari mediators. Tehran is awaiting a reply on its Hormuz plan, while a U.S. official says there will be no deal unless nuclear issues are addressed.",
                  "At the U.N. Security Council, ambassadors met as West Bank tensions rise and the Gaza plan stalls."]),
 ("Africa", ["The U.N. says it is gravely concerned by the deteriorating security situation across northern Ethiopia, where fighting is spreading across multiple fronts and disrupting humanitarian operations.",
             "At the General Assembly, South Sudan's envoy called for sanctions on her country to be lifted."]),
 ("Closing", ["That was the Upheal briefing. Follow the links on each story to read the original reporting.",
              "This audio was generated by a synthetic voice as a demonstration."]),
]

tmp = tempfile.mkdtemp()
def tts(text, i):
    a, w = f"{tmp}/{i}.aiff", f"{tmp}/{i}.wav"
    subprocess.run(["say", "-v", VOICE, "-r", "170", "-o", a, text], check=True)
    subprocess.run(["afconvert", "-f", "WAVE", "-d", "LEI16@22050", "-c", "1", a, w], check=True)
    return w

out = wave.open(f"{tmp}/all.wav", "wb"); out.setnchannels(1); out.setsampwidth(2); out.setframerate(22050)
rate, t, n = 22050, 0.0, 0
chapters, lines = [], []
def silence(sec):
    global t
    out.writeframes(b"\x00\x00" * int(rate * sec)); t += sec
for ci, (name, sentences) in enumerate(CHAPTERS):
    chapters.append(dict(title=name, start=round(t, 2)))
    for s in sentences:
        w = wave.open(tts(s, n), "rb"); n += 1
        dur = w.getnframes() / rate
        lines.append(dict(start=round(t, 2), end=round(t + dur, 2), text=s, chapter=ci))
        out.writeframes(w.readframes(w.getnframes())); t += dur; w.close()
        silence(0.45)
    silence(0.5)
out.close()
subprocess.run(["afconvert", "-f", "m4af", "-d", "aac", "-b", "64000", f"{tmp}/all.wav", "public/audio/briefing.m4a"], check=True)
json.dump(dict(duration=round(t, 2), voice=VOICE, chapters=chapters, lines=lines), open("src/data/briefing.json", "w"), ensure_ascii=False, indent=1)
print("duration", round(t, 1), "s;", len(lines), "lines;", os.path.getsize("public/audio/briefing.m4a") // 1024, "KB")
